### ISSUE TITLE
Complete the footer by adding the correct links

### ISSUE THREAD

**Issue by djoufson** [dotnetcameroon/website#16]
- social medias
- related pages

**Comment by ij2002** [comment]
Hi, I would like to be assigned to this issue

**Comment by djoufson** [comment]
@ij2002 here are the correct links to put on the footer:

- Discord: https://discord.gg/npkCMRgqdm
- Whatsapp: https://chat.whatsapp.com/KlBkiJX85Y8KFS28tIm1UU
- LinkedIn: https://www.linkedin.com/company/dotnetcameroon
- GitHub: https://github.com/dotnetcameroon
- Telegram: https://t.me/+cjXkPqigrZNkNDE0

Make sure to add a target="_blank" on each `a` tag of the social medias so that it opens a new tab when we click

**Comment by ij2002** [comment]
Hi, the current develop branch hasn't been building, should I continue from my old branch?
![Screenshot 2024-08-14 235022](https://github.com/user-attachments/assets/d03a7592-7a13-4dad-b3eb-d5a8ddc4f9d3)

**Comment by djoufson** [comment]
Let me check... Starting from the last update I made, I introduced a Sql Server Database. You will need more requirements to run it

**Comment by ij2002** [comment]
Sure! Do let me know when and how to proceed

**Comment by djoufson** [comment]
The README explains how to setup the env, let me know if you face some trouble, we can schedule a Google meet call, I am available rn
