### ISSUE TITLE
Fix the mobile navbar

### ISSUE THREAD

**Issue by djoufson** [dotnetcameroon/website#18]
When we scroll up to the threshold point, the nnavbar appears as expected but does not work.
The screenshot below showcases the open state of the navbar menu.

![IMG_2556](https://github.com/user-attachments/assets/2813ec83-f28c-4d04-a6a4-a02a66ce7851)

**Comment by ij2002** [comment]
hello, could i be assigned to fix this?

**Comment by djoufson** [comment]
> hello, could i be assigned to fix this?

Sure, thanks for the interest. First thing first, read the CONTRIBUTING file. Here is a quick recap of the steps to follow:
- fork the repository
- Create a branch from the branch `develop` with the issue name
- Write your code
- Open a pull request to merge into `develop`

Please make sure that your pull request goes in the `develop` branch and not `main`

**Comment by addygit123** [comment]
I want to contribute if you permit

**Comment by ij2002** [comment]
> > hello, could i be assigned to fix this?
> 
> Sure @ij2002, thanks for the interest. First thing first, read the CONTRIBUTING file. Here is a quick recap of the steps to follow:
> 
> * fork the repository
> * Create a branch from the branch `develop` with the issue name
> * Write your code
> * Open a pull request to merge into `develop`
> 
> Please make sure that your pull request goes in the `develop` branch and not `main`

Perfect!! I had already looked at the website as well as the CONTRIBUTING file and found it suitable. Will update as soon as possible!

**Comment by ij2002** [comment]
@djoufson Completed and have submitted a PR! Do you let me know if you would also want me help create a better looking navbar. Thank you for letting me work on this!
